### ISSUE TITLE
Vagrant fails to start with no code directory

### ISSUE THREAD

**Issue by megan-godfrey** [openflighthpc/openflight-vagrant-cluster#2]
Requires code directory within home directory

**Comment by mjtko** [comment]
Looks like this line could do with being fixed:

https://github.com/openflighthpc/openflight-vagrant-cluster/blob/068883a1fd82b7329cba7fcf42c15f563e384386/Vagrantfile#L17

Maybe include a `CODE_PATH.nil?` check to skip that block if there's no `~/code` directory.

**Comment by benarmston** [comment]
Vagrant still fails to start without a code directory, but now it once again fails with a helpful message directing the user to create the code directory.
